name: Push & PR Validation
on: 
  push:
    branches-ignore: [master, staging]
  pull_request:
    branches: [master, staging]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Run Commitlint
        run: npx commitlint --from HEAD~1 --to HEAD

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        node:
          - 10.x
          - 12.x
          - 14.x
          - 15.x

    runs-on: ${{ matrix.os }}

    name: Test on ${{ matrix.os }} - Node v${{ matrix.node }}
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test