name: Release
on:
  workflow_run:
    workflows: ["Push & Pull Request Validation"]
    branches: [master]
    types:
      - completed
      - requested

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node (semantic release)
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npm run release