name: Release
on:
  workflow_run:
    workflows: ["Push & Pull Request Validation"]
    branches: [ master, staging ]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node (semantic release)
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npm run release
        env:
          GITHUB_NPM_CONFIG_REGISTRY: 'https://npm.pkg.github.com/'
          GITHUB_NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org/'
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}