name: Release
on:
  push:
    branches: [ master, staging ]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GIT_AUTHOR_NAME: Joseph R Miles
      GIT_AUTHOR_EMAIL: joe@jrm.dev
    
    name: Run Semantic Release
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node (semantic release)
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npm run release
        env:
          GITHUB_NPM_CONFIG_REGISTRY: 'https://npm.pkg.github.com/'
          GITHUB_NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org/'
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}